import type { ComponentType } from "react";
import type { IconType } from "react-icons";
import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiPython,
  SiDjango,
  SiFlask,
  SiPhp,
  SiLaravel,
  SiOpenjdk,
  SiSpring,
  SiCplusplus,
  SiSharp,
  SiRuby,
  SiRubyonrails,
  SiGo,
  SiRust,
  SiSwift,
  SiKotlin,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiGraphql,
  SiDocker,
  SiKubernetes,
  SiGooglecloud,
  SiFirebase,
  SiVercel,
  SiGit,
  SiGithub,
  SiGitlab,
  SiTailwindcss,
  SiSass,
  SiBootstrap,
  SiVuedotjs,
  SiAngular,
  SiFigma,
  SiLinux,
  SiJquery,
  SiWordpress,
} from "react-icons/si";
import { FaAws, FaSalesforce } from "react-icons/fa6";

export interface TechIconOption {
  key: string;
  label: string;
  Icon: ComponentType<{ size?: number; className?: string }> | IconType;
}

export const TECH_ICON_OPTIONS: TechIconOption[] = [
  { key: "html5", label: "HTML5", Icon: SiHtml5 },
  { key: "css3", label: "CSS3", Icon: SiCss },
  { key: "javascript", label: "JavaScript", Icon: SiJavascript },
  { key: "typescript", label: "TypeScript", Icon: SiTypescript },
  { key: "react", label: "React", Icon: SiReact },
  { key: "nextjs", label: "Next.js", Icon: SiNextdotjs },
  { key: "redux", label: "Redux", Icon: SiRedux },
  { key: "nodejs", label: "Node.js", Icon: SiNodedotjs },
  { key: "express", label: "Express", Icon: SiExpress },
  { key: "python", label: "Python", Icon: SiPython },
  { key: "django", label: "Django", Icon: SiDjango },
  { key: "flask", label: "Flask", Icon: SiFlask },
  { key: "php", label: "PHP", Icon: SiPhp },
  { key: "laravel", label: "Laravel", Icon: SiLaravel },
  { key: "java", label: "Java", Icon: SiOpenjdk },
  { key: "spring", label: "Spring", Icon: SiSpring },
  { key: "cpp", label: "C++", Icon: SiCplusplus },
  { key: "csharp", label: "C#", Icon: SiSharp },
  { key: "ruby", label: "Ruby", Icon: SiRuby },
  { key: "rails", label: "Ruby on Rails", Icon: SiRubyonrails },
  { key: "go", label: "Go", Icon: SiGo },
  { key: "rust", label: "Rust", Icon: SiRust },
  { key: "swift", label: "Swift", Icon: SiSwift },
  { key: "kotlin", label: "Kotlin", Icon: SiKotlin },
  { key: "mysql", label: "MySQL", Icon: SiMysql },
  { key: "postgresql", label: "PostgreSQL", Icon: SiPostgresql },
  { key: "mongodb", label: "MongoDB", Icon: SiMongodb },
  { key: "redis", label: "Redis", Icon: SiRedis },
  { key: "sqlite", label: "SQLite", Icon: SiSqlite },
  { key: "graphql", label: "GraphQL", Icon: SiGraphql },
  { key: "docker", label: "Docker", Icon: SiDocker },
  { key: "kubernetes", label: "Kubernetes", Icon: SiKubernetes },
  { key: "aws", label: "AWS", Icon: FaAws },
  { key: "gcp", label: "Google Cloud", Icon: SiGooglecloud },
  { key: "firebase", label: "Firebase", Icon: SiFirebase },
  { key: "vercel", label: "Vercel", Icon: SiVercel },
  { key: "git", label: "Git", Icon: SiGit },
  { key: "github", label: "GitHub", Icon: SiGithub },
  { key: "gitlab", label: "GitLab", Icon: SiGitlab },
  { key: "tailwind", label: "Tailwind CSS", Icon: SiTailwindcss },
  { key: "sass", label: "Sass", Icon: SiSass },
  { key: "bootstrap", label: "Bootstrap", Icon: SiBootstrap },
  { key: "vue", label: "Vue.js", Icon: SiVuedotjs },
  { key: "angular", label: "Angular", Icon: SiAngular },
  { key: "salesforce", label: "Salesforce", Icon: FaSalesforce },
  { key: "figma", label: "Figma", Icon: SiFigma },
  { key: "linux", label: "Linux", Icon: SiLinux },
  { key: "jquery", label: "jQuery", Icon: SiJquery },
  { key: "wordpress", label: "WordPress", Icon: SiWordpress },
];

export const TECH_ICON_MAP: Record<string, TechIconOption["Icon"]> =
  Object.fromEntries(TECH_ICON_OPTIONS.map(({ key, Icon }) => [key, Icon]));

export const getTechIconLabel = (key?: string): string | undefined => {
  return TECH_ICON_OPTIONS.find((option) => option.key === key)?.label;
};
